WIiR_APP/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/doc/', include('django.contrib.admindocs.urls')),
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('units/', include('units.urls')),
                  path('investments/', include('investments.urls')),
                  path('contracts/', include('contracts.urls')),
                  path('contractors/', include('contractors.urls')),
                  path('invoices/', include('invoices.urls')),
                  path('permanentManagement/', include('permanentmanagement.urls')),
                  path('genre/', include('cpvdict.urls')),
                  path('donations/', include('donations.urls')),
                  path('inspections/', include('constructioninspections.urls')),
                  path('fixedAsset/', include('fixedasset.urls')),
                  path('operationalNeeds/', include('operationalneedsrecords.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('businessFlats/', include('businessflats.urls')),
                  path('login/', auth_views.LoginView.as_view(), name='login'),
                  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path('', include('main.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contractors/urls.py
from django.urls import path, re_path
from .views import ContractorsListView, AddNewContractorView, EditContractorView, ShowInformationView

app_name = "contractors"
urlpatterns = [
    path("new/", AddNewContractorView.as_view(), name="new_contractor"),
    path("edit/<slug:slug>/", EditContractorView.as_view(), name="edit_contractor"),
    re_path("info/(?P<id>\d+)/$", ShowInformationView.as_view(), name="show_information"),
    path("", ContractorsListView.as_view(), name="contractor_list")
]

cpvdict/urls.py
from django.urls import path, re_path
from cpvdict.views import CpvDictionary, GenericMenu, OrderListView, ShowOrderInfo, NewOrderView, ConstructionWorksClassificationListView, \
    ShowInfoWorkObject, EditOrderView, ArchiveYearListView, OrderArchiveListView, \
    ConstructionWorksArchiveList, GenreArchiveView

app_name = 'cpvdict'
urlpatterns = [
    path('dictCPV/', CpvDictionary.as_view(), name='cpvlist'),
    path('genreTree/', GenericMenu.as_view(), name='type_expense_list'),
    path('buildingWorks/', ConstructionWorksClassificationListView.as_view(), name='type_work_list'),
    re_path('info/(?P<id>\d+)>/(?P<year>[0-9]{4})/$', ShowInfoWorkObject.as_view(), name='show_information_work_object'),
    path('orderList/', OrderListView.as_view(), name='order_list'),
    re_path('info/(?P<id>\d+)/$', ShowOrderInfo.as_view(), name='show_order_info_popup'),
    path('new_order/', NewOrderView.as_view(), name='new_order'),
    re_path('editOrder/(?P<id>\d+)/$', EditOrderView.as_view(), name='edit_order'),
    path('archiveListYear/', ArchiveYearListView.as_view(), name='make_archive_year_list'),
    re_path('archiveListOrder/(?P<year>\d+)/$', OrderArchiveListView.as_view(), name='create_order_archive'),
    re_path('archiveBuildingWorks/(?P<year>\d+)/$', ConstructionWorksArchiveList.as_view(), name='create_type_work_list_archive'),
    re_path('genreTreeArchive/(?P<year>\d+)/$', GenreArchiveView.as_view(), name='create_genre_archive')
]

main/urls.py
from django.urls import path, re_path
from main.views import ListRegisterView, WelcomeView, SecretariatSiteView, EmployersListView, CommandListView, \
    AccessToModulesView, TelephoneListView, ShowTeamsListView, NewTeamView, EditTeamView, \
    NewEmployerView, EditEmployerView, AddCommandView, EditCommandView, DeleteCommandView, \
    NewSecretariatNumberView, EditSecretariatNumberView, DeleteSecretariatNumberView, EditRentCarView, DeleteRentCar, \
    NewRentCatView, NecesseryFileView, DownloadFilesView, AddUploadFilesView, DeleteUploadFile

app_name = 'main'
urlpatterns = [
    path('secretariat/', SecretariatSiteView.as_view(), name='make_secretariat_site'),
    path('addRentCar/', NewRentCatView.as_view(), name='add_rent_car'),
    re_path('rentCar/(?P<id>\d+)/$', EditRentCarView.as_view(), name='edit_rent_car'),
    re_path('deleteRentCar/(?P<id>\d+)/$', DeleteRentCar.as_view(), name='delete_rent_car'),
    path('addSecretariatInfo/', NewSecretariatNumberView.as_view(), name='add_secretariat_number'),
    re_path('editSecretariatInfo/(?P<id>\d+)/$', EditSecretariatNumberView.as_view(), name='edit_secretariat_number'),
    re_path('delete_secretariat/(?P<id>\d+)/$', DeleteSecretariatNumberView.as_view(),
            name='delete_secretariat_number'),
    path('secretariat/teams/', ShowTeamsListView.as_view(), name='show_teams_list'),
    path('secretariat/teams/add/', NewTeamView.as_view(), name='add_team_popup'),
    re_path('secretariat/teams/edit/(?P<id>\d+)/$', EditTeamView.as_view(), name='edit_team_popup'),
    path('secretariat/employers/', EmployersListView.as_view(), name='show_employers_list'),
    path('secretariat/employers/add/', NewEmployerView.as_view(), name='add_employer_popup'),
    re_path('secretariat/employers/edit/(?P<id>\d+)/$', EditEmployerView.as_view(), name='edit_employer_popup'),
    path('secretariat/commands/', CommandListView.as_view(), name='show_command_list'),
    path('secretariat/commands/add/', AddCommandView.as_view(), name='add_command_popup'),
    re_path('secretariat/commands/edit/(?P<id>\d+)/$', EditCommandView.as_view(), name='edit_command_popup'),
    re_path('secretariat/commands/delete/(?P<id>\d+)/$', DeleteCommandView.as_view(), name='delete_command_popup'),
    path('access/', AccessToModulesView.as_view(), name='give_access_to_modules'),
    path('registerList/', ListRegisterView.as_view(), name='make_list_register'),
    path('telephones/', TelephoneListView.as_view(), name='telephone_list'),
    path('files/', NecesseryFileView.as_view(), name='files'),
    path('secretariat/upload_files/', DownloadFilesView.as_view(), name='download_files'),
    path('secretariat/upload_files/add/', AddUploadFilesView.as_view(), name='add_download_files_popup'),
    re_path('secretariat/upload_file/delete/(?P<id>\d+)/$', DeleteUploadFile.as_view(), name='delete_download_file'),
    path('', WelcomeView.as_view(), name='welcome')

]

cpvdict/models.py
from django.db import models
from units.models import Unit
from contractors.models import Contractor
from main.models import Employer


# Create your models here.
class Typecpv(models.Model):
    class Meta:
        verbose_name = "CPV"
        verbose_name_plural = "R.06 - Słownik CPV"

    no_cpv = models.CharField(max_length=10)
    name = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.no_cpv}"


class TypeOrder(models.Model):
    class Meta:
        verbose_name = "Rodzaj zamowienia"
        verbose_name_plural = "R.03 - Rodzaj zamówienia"

    type = models.CharField("Rodzaj zamówienia", max_length=20, null=True)

    def __str__(self):
        return f"{self.type}"


class Genre(models.Model):
    class Meta:
        verbose_name = "Przedmiot zamówienia"
        verbose_name_plural = "R.02 - Klasyfikacja rodzajowa"
        ordering = ["name_id"]

    name_id = models.CharField("ID", max_length=4, unique=True)
    name = models.CharField("Ogólna nazwa przedmiotu zamówienia w ujęciu rodzajowym", max_length=200)
    cpv = models.ManyToManyField("cpvdict.Typecpv", verbose_name="Kody CPV", related_name="Genre")
    sum = models.DecimalField("Suma zamówień", max_digits=8, decimal_places=2, null=True, blank=True)
    remain = models.DecimalField("Pozostało", max_digits=8, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f"({self.name_id}) {self.name}"


class Tax(models.Model):
    class Meta:
        verbose_name = "Podatek Vat"
        verbose_name_plural = "R.04 - Rodzaje podatków vat"

    vat = models.SmallIntegerField("Podatek [%]", default=0)

    def __str__(self):
        return f"{self.vat}%"


class OrderLimit(models.Model):
    class Meta:
        verbose_name = "Limit zamówień"
        verbose_name_plural = "R.01 - Limit zamówień"
        ordering = ["-year"]

    year = models.IntegerField("Rok", unique=True)
    euro_exchange_rate = models.DecimalField("Kurs euro", max_digits=5, decimal_places=4)
    limit_euro = models.DecimalField("Limit euro", max_digits=10, decimal_places=2)
    limit_netto = models.DecimalField("Limit zamówień netto", max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.year} - {self.euro_exchange_rate} ({self.limit_euro}) - {self.limit_netto}zł."


class Order(models.Model):
    class Meta:
        verbose_name = "Zamówienie"
        verbose_name_plural = "R.05 - Zamówienia"
        ordering = ["-date"]

    date = models.DateField("Data")
    no_order = models.CharField("Nr zlecenia", max_length=15, blank=True, default="", unique=True)
    sum_netto = models.DecimalField("Kwota netto", max_digits=8, decimal_places=2)
    vat = models.ForeignKey(Tax, on_delete=models.CASCADE, verbose_name="Podatek", related_name="order")
    sum_brutto = models.DecimalField("Kwota brutto", max_digits=10, decimal_places=2, null=True, blank=True)
    typeorder = models.ForeignKey(TypeOrder, on_delete=models.CASCADE, verbose_name="Rodzaj zamówienia",
                                  related_name="order")
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name="order", verbose_name="ID rodzajowości")
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE, verbose_name="Kontrahent",
                                   related_name="order")
    unit = models.ManyToManyField(Unit, related_name="order", verbose_name="Obiekt")
    brakedown = models.BooleanField("Awaria")
    worker = models.ForeignKey(Employer, on_delete=models.CASCADE, verbose_name="Branżysta", related_name="order")
    content = models.TextField("Zakres", blank=True, default="")
    create_date = models.DateField("Data dodania", auto_now_add=True)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, related_name="order")

    def __str__(self):
        return f"Zlecenie nr {self.no_order} z dnia {self.date} (rodzaj: {self.typeorder})"

cpvdict/forms.py
from django.forms import ModelForm, DateInput, Textarea
from main.forms import DateField
from cpvdict.models import Typecpv, OrderLimit, Order, Tax


class TypecpvForm(ModelForm):
    class Meta:
        model = Typecpv
        fields = ['no_cpv', 'name']
        labels = {'no_cpv': 'Kod CPV', 'name': 'Nazwa przedmiotu zamówienia wg CPV'}


class OrderLimitForm(ModelForm):
    class Meta:
        model = OrderLimit
        fields = ['year', 'euro_exchange_rate', 'limit_euro', 'limit_netto']
        labels = {'year': 'Rok', 'euro_exchange_rate': 'Kurs euro', 'limit_netto': 'Limit zamówień netto'}


class TaxForm(ModelForm):
    class Meta:
        model = Tax

        fields = ('vat',)
        labels = {'vat': 'Podatek'}


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['date', 'no_order', 'sum_netto', 'vat', 'sum_brutto', 'typeorder', 'genre', 'unit', 'contractor',
                  'brakedown', 'worker', 'content']
        exclude = ['author', 'create_date']
        labels = {'date': 'Data', 'no_order': 'Nr zamówienia', 'sum_netto': 'Kwota netto', 'vat': 'vat',
                  'sum_brutto': 'kwota brutto', 'typeorder': 'Rodzaj zamówienia', 'genre': 'ID Rodzajowości',
                  'unit': 'Jednostka', 'contractor': 'Wykonawca', 'brakedown': 'Awaria', 'content': 'Zakres'}

        widgets = {'date': DateField(),
                   'content': Textarea(attrs={'rows': 5})}

cpvdict/templates/cpvdict/archive_list_year_order_popup.html
{% load static%}
{%block content%}
<div class=container">
    <h5 class="text-center my-3">Archiwum zleceń</h5>
    <div class="col m-2">
        {%for year in year_order_list%}
        <a href="{%url 'cpvdict:create_order_archive' year%}"><button type="button" class="btn btn-outline-dark m-2">Rok: {{year}}</button></a>
        {%endfor%}
    </div>
</div>
{%endblock%}

cpvdict/templates/cpvdict/archive_order_list.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block title %} Ewidencja zleceń na rok {{year}} {% endblock %}
{% block content %}
<div class="row">
     <div class="col-md-3 moj-button-left">
         <a href="{%url 'cpvdict:type_expense_list'%}">
            <button type="button" class="btn btn-outline-primary my-btn">
                <span class="bi bi-chevron-compact-left">Cofnij</span>
            </button>
         </a>
     </div>
    <div class="col-md-6 text-center">
        <h4>Zlecenia za {{year}} rok</h4>
    </div>
    <div class="col-md-3 moj-button-right">
        <a href="{%url 'cpvdict:create_genre_archive' year%}"><button class="btn btn-outline-primary button-choise-contracts my-btn">Rodzajowość {{year}}&nbsp;r.</button>
            </a>
    </div>
</div>
<div class="mt-3">
    <div class="row">
        <div class="col-md-3 align-self-end">
            <p class=""><span>Liczba zleceń: </span><span class="badge text-white info badge-pill">{{ordersum}}</span></p>
        </div>
        <div class="col-md-6">
            <section class="w-100 pb-4 d-flex justify-content-center align-items-center flex-column">
                    <form id="form-search" method="get">
                        <div class="row">
                        <div class="col-md-3">
                            <div class="">
                                <label class="control-label" for="date_from">Data zlecenia od</label>
                                <div class=" ">
                                    <input type="date" name="from" class="form-control" id="date_from" value="{{date_from}}">
                                </div>
                            </div>
                        </div>
                    <div class="col-md-3">
                        <div class="">
                            <label class="control-label" for="date_to">Data zlecenia do</label>
                            <div class=" ">
                                <input type="date" name="to" class="form-control" id="date_to" value="{{date_to}}">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5 d-flex align-items-end">
                        <div class="input-group">
                            <input name="q" id="q" type="text" class="form-control rounded" placeholder="szukaj zlecenia" aria-label="Search" aria-describedby="search-addon" value="{%if query%}{{q}}{%endif%}">
                        <button id="searchButton" style="{%if query%}display:none;{%endif%}" type="submit" class="btn btn-outline-primary my-btn">Szukaj</button>
                        <button id="cleanButton"  style="{%if not query%}display:none;{%endif%}" type="button" class="btn btn-outline-primary my-btn" onclick="cleanSearch()">Wyczyść</button>
                        </div>
                    </div>
                    </div>
                    </form>
            </section>
        </div>
        <div class="col-md-3 moj-button-right">
            <a href="{%url 'cpvdict:create_type_work_list_archive' year%}">
                <button class="btn btn-outline-primary button-choise-contracts my-btn">Roboty budowlane</button>
            </a>
        </div>
    </div>
</div>
<table class="table table-hover my-table mt-2">
    <thead>
    <tr class="my-table-tr">
        <th align="center" valign="middle" width="40" scope="col" class="text-center">L.p.</th>
        <th align="center" valign="middle" width="150" scope="col" class="text-center">Data</th>
        <th align="center" valign="middle" width="150" scope="col" class="text-center">Nr. dokumentu</th>
        <th align="center" valign="middle" width="320" scope="col" class="text-center">Wykonawca</th>
        <th align="center" valign="middle" width="200" scope="col" class="text-center">Kwota brutto</th>
        <th align="center" valign="middle" width="200" scope="col" class="text-center">ID rodzajowości</th>
        <th align="center" valign="middle" width="100" scope="col" class="text-center">Awaria</th>
        <th align="center" valign="middle" width="auto" scope="col" class="text-center">Branżysta</th>
        <th valign="middle" width="auto" scope="col" class="text-center"></th>
    </tr>
    </thead>
    <tbody>
    {%for order in orders %}
    <tr class="my-table-tr">
        <td align="center" valign="middle" scope="row"></td>
        <td align="center" valign="middle">{{order.date|date:"d.m.Y"}} r.</td>
        <td align="left" valign="middle" title="{{order.worker}}">{{order.no_order|default_if_none:'---'}}</td>
        <td align="left" valign="middle"><span>{{order.contractor.name}}</span><br><small>{{order.contractor.address}}, {{order.contractor.zip_code}} {{order.contractor.city}}</small></td>
        <td align="right" valign="middle"><span data-toggle="info" title="Kwota netto: {{order.sum_netto|intcomma}}&nbsp;zł.&#010;(vat: {{order.vat}})">{{order.sum_brutto|intcomma}}&nbspzł.</span></td>
        <td align="center" valign="middle"><span data-toggle="info" title="{{order.typeorder}}">{{order.genre.name_id}}</span></td>
        <td align="center" valign="middle">{% if order.brakedown  %} <i class="bi bi-check2-circle text-success icon-check"></i> {%else%} --- {%endif%}</td>
        <td align="center" valign="middle"><span>{{order.worker}}</span></td>
        <td align="right" valign="middle">
            <button data-toggle="info" title="Pokaż" type="button" data-url="{%url 'cpvdict:show_order_info_popup' order.id%}" class="btn btn-outline-success mx-2" onclick="openModal(this)"><i
                    class="bi bi-info-lg"></i>
            </button>
        </td>
    </tr>
    {%endfor%}
    </tbody>
    <tfoot>
    <tr>
        <th colspan="5">Wydział Inwestycji i Remontów KWP w Poznaniu</th>
    </tr>
    </tfoot>
</table>
<!--Pagination-->
{%if search%}
<nav aria-labelledby="Page navigation">
    <ul class="pagination justify-content-center">
        {%if orders.has_previous%}
        <li class="page-item">
            <a class="page-link" href="?page={{orders.previous_page_number}}">Poprzednia</a>
        </li>
        {%else%}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Poprzednia</a>
        </li>
        {%endif%}
        {%for i in orders.paginator.page_range%}
        {%if orders.number == i%}
        <li class="page-item active" aria-current="page">
            <span class="page-link">
                {{i}}
                <span class="sr-only"></span>
            </span>
        </li>
        {%else%}
        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
        {%endif%}
        {%endfor%}
        {%if orders.has.next%}
        <li class="page-item">
            <a class="page-link" href="?page={{orders.next_page_number}}">Następna</a>
        </li>
        {%else%}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Następna</a>
        </li>
        {%endif%}
    </ul>
</nav>
{%endif%}
<!-- Modal -->
<div class="modal fade" id="orderInformationModal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>
<script>
     document.getElementById("button-units").classList.remove("active");
     document.getElementById("button-record").classList.remove("active");
     document.getElementById("button-secretariat").classList.remove("active");
     document.getElementById("button-cpv").classList.add("active");
     document.getElementById("button-investments").classList.remove("active");

     function openModal(button){
        var url = $(button).data("url");
        $("#orderInformationModal .modal-content").load(url);
        $("#orderInformationModal").modal("show");
        }

    function submitForm(){
        $("#submitButton").closest("form").submit();
        }

    function cleanSearch(){
        $("#q").val("");
        $("#date_from").val("");
        $("#date_to").val("");
        $("#form-search").submit();
        }
</script>
{% endblock %}

cpvdict/templates/cpvdict/info_work_popup.html
{%load static%}
{%load humanize%}
{%load bootstrap%}
{%block content%}
<div class="container ">
<form class="m-2 p-4" method="get" action="{% url 'cpvdict:show_information_work_object' id year %}">
    {%csrf_token%}
    <div class="container">
        <h5 class="text-center">{{work_object}}</h5>
        {% if orders %}
        <h6 class="mt-4"><b>Zlecenia z {{year}} roku.</b></h6>
        {% else %}
        <h6 class="mt-4"><b>Brak zleceń</b></h6>
        {%endif%}
        <ol>
        {% for order in orders.all %}
            <li><span>{{order.no_order}} z dnia {{order.date}} r. Wartość zlecenia: <b>{{order.sum_netto|intcomma}} zł. netto</b> - Branżysta: {{order.worker}}</span></li>
        {%endfor%}
        </ol>
    </div>
</form>
</div>
{%endblock%}

cpvdict/templates/cpvdict/order_form.html
{% extends 'base.html'%}
{% load bootstrap %}
{% load static %}
{% block title %} Zlecenie {% endblock %}
{% block content%}
<div class="container col-md-6 mb-4">
    <div class="row">
        <div class="col-md-3"><a href="{%url 'cpvdict:order_list'%}">
            <button class="btn btn-outline-primary my-btn"><span class="bi bi-chevron-compact-left">Cofnij</span></button></a>
        </div>
        <div class="col-md-6">
            <h4 class="text-center">{%if new%}Nowe zlecenie{%else%}Edycja zlecenia {{no_order}}{%endif%}</h4>
        </div>
    </div>
</div>
<div class="container  col-md-6">
    <form method="post">
        {%csrf_token%}
        <div class="row">
            <div class="col-md-4 px-2 my-1">{{ order_form.date|bootstrap }}</div>
            <div class="col-md-4 px-2 my-1">{{ order_form.no_order|bootstrap }}</div>
            <div class="col-md-4 px-2 mt-1">{{ order_form.worker|bootstrap }}</div>
            <div class="col-md-3 px-2 my-1">{{ order_form.sum_netto|bootstrap }}</div>
            <div class="col-md-2 px-2 my-1">{{ order_form.vat|bootstrap }}</div>
            <div class="col-md-3 px-2 my-1">
                <div class="form-group">
                    <label class="control-label" for="id_sum_brutto">kwota brutto</label>
                    <div class="">
                        <input type="number" name="sum_brutto" step="0.01" class=" form-control" required="" id="id_sum_brutto" value="{{ order_form.sum_brutto.value}}" readonly>
                    </div>
                </div>
            </div>
            <div class="col-md-4 my-1 pt-4"  data-toggle="info" title="Zaznacz jeśli zamówienie jest w trybie awaryjnym">
                <div class="">
                    <div class=" form-control">
                        <div class="checkbox">
                        <label>
                            <input type="checkbox" name="brakedown" id="id_brakedown"> <span>Awaria</span>
                        </label>
                    </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12 px-2 my-1">{{ order_form.contractor|bootstrap }}</div>
            <div class="col-md-4 px-2 my-1">{{ order_form.typeorder|bootstrap }}</div>
            <div class="col-md-8 px-2 my-1">{{ order_form.genre|bootstrap }}</div>
            <div class="col-md-12 p-2">{{ order_form.unit|bootstrap }}</div>
            <div class="col-md-12 px-2 mt-3 text-center">{{ order_form.content|bootstrap}}</div>
                <div class="col-md-12 moj-button-right my-3">
                    <button type="submit" class="btn btn-outline-primary my-btn">
                        <span class="bi bi-save2"> Dodaj</span>
                    </button>
                </div>
            </div>
    </form>
</div>
<script>
<!--     zmienić wartość, jeśli zmieni się id rodzajowości dla robót budowlanych-->
     genereWorkId = '3';

    function reinitUnits(){
        $('#id_unit').select2('destroy');
        if($('#id_typeorder').val() == genereWorkId && $('#id_genre').val() == genereWorkId){
            $("#id_unit").select2({placeholder:'Dodaj jednostki', multiple: false});
        } else {
            $("#id_unit").select2({placeholder:'Dodaj jednostki', multiple: true});
        }
    }

    function setGenereValue(){
        if($('#id_typeorder').val() == genereWorkId){
            $("#id_genre").unbind("change")
            $("#id_genre").val(genereWorkId).change();
            $("#id_genre").change(function(){setTypeOrderValue()})
        } else if (currentTypeOrderValue == genereWorkId){
            $("#id_genre").unbind("change")
            $("#id_genre").val(null).change();
            $("#id_genre").change(function(){setTypeOrderValue()})
        }
        currentTypeOrderValue = $('#id_typeorder').val();
        currentGenereValue = $('#id_genre').val();

        reinitUnits();
    }

    function setTypeOrderValue(){
        if($('#id_genre').val() == genereWorkId){
                                                                        // żeby uniknąć pętli eventów
            $("#id_typeorder").unbind("change")                         // odpinamy nasłuchiwanie change dla type order
            $("#id_typeorder").val(genereWorkId).change();              // ustawiamy wartosc type order (wymaga odpalenia eventu change)
            $("#id_typeorder").change(function(){setGenereValue();})    // ponownie ustawiamy nasluchiwanie change

        } else if (currentGenereValue == genereWorkId){
            $("#id_typeorder").unbind("change")
            $("#id_typeorder").val(null).change();
            $("#id_typeorder").change(function(){setGenereValue();})
        }
        currentTypeOrderValue = $('#id_typeorder').val();
        currentGenereValue = $('#id_genre').val();

        reinitUnits();
    }

     $(document).ready(function(){

        document.getElementById("button-units").classList.remove("active");
        document.getElementById("button-record").classList.remove("active");
        document.getElementById("button-secretariat").classList.remove("active");
        document.getElementById("button-cpv").classList.add("active");
        document.getElementById("button-investments").classList.remove("active");

        //zainicjowanie poprawnego typu selecta dla jednostek
        if($('#id_typeorder').val() == genereWorkId && $('#id_genre').val() == genereWorkId){
            $("#id_unit").select2({placeholder:'Dodaj jednostki', multiple: false});
        } else {
            $("#id_unit").select2({placeholder:'Dodaj jednostki', multiple: true});
        }

        // zapisana bieżąca wartość rodzaju zamówienia
        currentTypeOrderValue = $('#id_typeorder').val();

        // zapisana bieżąca wartość id rodzajowości
        currentGenereValue = $('#id_genre').val();

        // ustawiamy nasłuchiwanie eventu change dla type order
        $('#id_typeorder').change(function(){
            setGenereValue();
        })

        // ustawiamy nasłuchiwanie eventu change dla genere
        $('#id_genre').change(function(){
            setTypeOrderValue();
        })
    })
</script>
{% endblock %}