WIiR_APP/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/doc/', include('django.contrib.admindocs.urls')),
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('units/', include('units.urls')),
                  path('investments/', include('investments.urls')),
                  path('contracts/', include('contracts.urls')),
                  path('contractors/', include('contractors.urls')),
                  path('invoices/', include('invoices.urls')),
                  path('permanentManagement/', include('permanentmanagement.urls')),
                  path('genre/', include('cpvdict.urls')),
                  path('donations/', include('donations.urls')),
                  path('inspections/', include('constructioninspections.urls')),
                  path('fixedAsset/', include('fixedasset.urls')),
                  path('operationalNeeds/', include('operationalneedsrecords.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('businessFlats/', include('businessflats.urls')),
                  path('login/', auth_views.LoginView.as_view(), name='login'),
                  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path('', include('main.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

invoices/urls.py
from django.urls import path, re_path
from .views import MenuInvoicesView, BuyInvoicesListView, BuyInvoicesListArchiveView, NewInvoiceBuyView, \
    SellInvoicesListView, SellInvoicesListArchiveView, NewInvoiceSellView, EditInvoiceSellView, \
    EditInvoiceSellArchiveView, EditInvoiceBuyView, \
    MakeVerificationView, ShowInfoBuyView, ShowInfoSellView, CorrectiveNoteListView, CorrectiveNoteListArchiveView, \
    ShowCorrectiveNoteInfoView, CorrectiveNoteCreateView, CorrectiveNoteUpdateView, EditNoteArchiveView, \
    MakePDFFromInvoicesSellView, AddItemsInvoiceBuyView, \
    DeleteItemsInvoiceBuyView, \
    DeleteInvoiceBuyView

app_name = "invoices"
urlpatterns = [
    path("menu/", MenuInvoicesView.as_view(), name="menu_invoices"),
    # Wydatki
    path("buyList/", BuyInvoicesListView.as_view(), name="buy_invoices_list"),
    re_path("infoBuy/(?P<id>\d+)/$", ShowInfoBuyView.as_view(), name="show_info_buy"),
    re_path("archiveBuy/(?P<year>[0-9]{4})/$", BuyInvoicesListArchiveView.as_view(), name="buy_invoices_list_archive"),
    path("newInvoice_buy/", NewInvoiceBuyView.as_view(), name="new_invoice_buy"),
    re_path("editInvoice_buy/(?P<id>\d+)/$", EditInvoiceBuyView.as_view(), name="edit_invoice_buy"),
    re_path("deleteInvoice_by/(?P<id>\d+)/$", DeleteInvoiceBuyView.as_view(), name="delete_invoice_buy"),
    re_path("addInvoiceItem/(?P<id>\d+)/$", AddItemsInvoiceBuyView.as_view(), name="add_items_invoice_buy"),
    re_path("deleteItem/(?P<id>\d+)/(?P<invoice_id>\d+)/$", DeleteItemsInvoiceBuyView.as_view(),
            name="delete_items_invoice_buy"),
    # Sprzedaż
    path("recordFvSell/", SellInvoicesListView.as_view(), name="sell_invoices_list"),
    re_path("infoSell/(?P<id>\d+)/$", ShowInfoSellView.as_view(), name="show_info_sell"),
    re_path("archiveSell/(?P<year>[0-9]{4})/$", SellInvoicesListArchiveView.as_view(),
            name="sell_invoices_list_archive"),
    path("newInvoiceSell/", NewInvoiceSellView.as_view(), name="new_invoice_sell"),
    re_path("editInvoiceSell/(?P<id>\d+)/$", EditInvoiceSellView.as_view(), name="edit_invoice_sell"),
    re_path("editInvoiceSellArchiwe/(?P<id>\d+)/$", EditInvoiceSellArchiveView.as_view(),
            name="edit_invoice_sell_archive"),
    path("trezor/", MakeVerificationView.as_view(), name="make_verification"),
    # Noty księgowe
    path("recordAccountingNote/", CorrectiveNoteListView.as_view(), name="corrective_note_list"),
    re_path("infoNote/(?P<id>\d+)/$", ShowCorrectiveNoteInfoView.as_view(), name="show_info_note"),
    re_path("recordAccountingNoteArchive/(?P<year>[0-9]{4})/$", CorrectiveNoteListArchiveView.as_view(),
            name="corrective_note_list_archive"),
    path("newAccountingNote/", CorrectiveNoteCreateView.as_view(), name="new_note"),
    re_path("editAccountingNote/(?P<id>\d+)/$", CorrectiveNoteUpdateView.as_view(), name="edit_note"),
    re_path("editAccountingNoteArchive(?P<id>\d+)/$", EditNoteArchiveView.as_view(), name="edit_note_archive"),
    path("create_pdf/<int:year>/ ", MakePDFFromInvoicesSellView.as_view(), name="make_pdf_from_invoices_sell")
]

main/urls.py
from django.urls import path, re_path
from main.views import ListRegisterView, WelcomeView, SecretariatSiteView, EmployersListView, CommandListView, \
    AccessToModulesView, TelephoneListView, ShowTeamsListView, NewTeamView, EditTeamView, \
    NewEmployerView, EditEmployerView, AddCommandView, EditCommandView, DeleteCommandView, \
    NewSecretariatNumberView, EditSecretariatNumberView, DeleteSecretariatNumberView, EditRentCarView, DeleteRentCar, \
    NewRentCatView, NecesseryFileView, DownloadFilesView, AddUploadFilesView, DeleteUploadFile

app_name = 'main'
urlpatterns = [
    path('secretariat/', SecretariatSiteView.as_view(), name='make_secretariat_site'),
    path('addRentCar/', NewRentCatView.as_view(), name='add_rent_car'),
    re_path('rentCar/(?P<id>\d+)/$', EditRentCarView.as_view(), name='edit_rent_car'),
    re_path('deleteRentCar/(?P<id>\d+)/$', DeleteRentCar.as_view(), name='delete_rent_car'),
    path('addSecretariatInfo/', NewSecretariatNumberView.as_view(), name='add_secretariat_number'),
    re_path('editSecretariatInfo/(?P<id>\d+)/$', EditSecretariatNumberView.as_view(), name='edit_secretariat_number'),
    re_path('delete_secretariat/(?P<id>\d+)/$', DeleteSecretariatNumberView.as_view(),
            name='delete_secretariat_number'),
    path('secretariat/teams/', ShowTeamsListView.as_view(), name='show_teams_list'),
    path('secretariat/teams/add/', NewTeamView.as_view(), name='add_team_popup'),
    re_path('secretariat/teams/edit/(?P<id>\d+)/$', EditTeamView.as_view(), name='edit_team_popup'),
    path('secretariat/employers/', EmployersListView.as_view(), name='show_employers_list'),
    path('secretariat/employers/add/', NewEmployerView.as_view(), name='add_employer_popup'),
    re_path('secretariat/employers/edit/(?P<id>\d+)/$', EditEmployerView.as_view(), name='edit_employer_popup'),
    path('secretariat/commands/', CommandListView.as_view(), name='show_command_list'),
    path('secretariat/commands/add/', AddCommandView.as_view(), name='add_command_popup'),
    re_path('secretariat/commands/edit/(?P<id>\d+)/$', EditCommandView.as_view(), name='edit_command_popup'),
    re_path('secretariat/commands/delete/(?P<id>\d+)/$', DeleteCommandView.as_view(), name='delete_command_popup'),
    path('access/', AccessToModulesView.as_view(), name='give_access_to_modules'),
    path('registerList/', ListRegisterView.as_view(), name='make_list_register'),
    path('telephones/', TelephoneListView.as_view(), name='telephone_list'),
    path('files/', NecesseryFileView.as_view(), name='files'),
    path('secretariat/upload_files/', DownloadFilesView.as_view(), name='download_files'),
    path('secretariat/upload_files/add/', AddUploadFilesView.as_view(), name='add_download_files_popup'),
    re_path('secretariat/upload_file/delete/(?P<id>\d+)/$', DeleteUploadFile.as_view(), name='delete_download_file'),
    path('', WelcomeView.as_view(), name='welcome')

]

invoices/models.py
from django.db import models
from enum import Enum
from contractors.models import Contractor
from units.models import County
from main.models import Employer
from sourcefinancing.models import FinanceSource
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
import re
import datetime


class DocumentsTypeEnum(Enum):
    FAKTURA = "Faktura"
    KOREKTA = "Korekta"
    NOTA_KORYGUJACA = "Nota korygująca"


class DocumentTypes(models.Model):
    class Meta:
        verbose_name = "Rodzaj dokumentu księgowego"
        verbose_name_plural = "F.05 - Rodzaje dokumentów księgowych"

    type = models.CharField("Typ dokumentu", max_length=20)

    def __str__(self):
        return f"{self.type}"


def validate_period(value):
    pattern = r'^\d{4}-\d{2}$'  # Wzorzec daty "YYYY-MM"
    if not re.match(pattern, value):
        raise ValidationError('Nieprawidłowy format daty. Oczekiwany format: YYYY-MM.')


class InvoiceSell(models.Model):
    class Meta:
        verbose_name = "Faktura sprzedaży"
        verbose_name_plural = "F.01 - Faktury - sprzedaż"
        ordering = ["-date"]

    relatedName = "invoicesell"

    date = models.DateField("Data wystawienia")
    no_invoice = models.CharField("Nr. faktury", max_length=11)
    doc_types = models.ForeignKey(DocumentTypes, null=False, blank=False, on_delete=models.CASCADE,
                                  verbose_name="Rodzaj dokumentu", related_name=relatedName)
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE, verbose_name="Kontrahent",
                                   related_name=relatedName)
    sum = models.DecimalField("Kwota [zł]", max_digits=10, decimal_places=2, null=True, blank=True)
    county = models.ForeignKey(County, on_delete=models.CASCADE, verbose_name="Powiat", related_name=relatedName)
    date_of_payment = models.DateField("Termin płatności")
    period_from = models.CharField(verbose_name="Okres od", max_length=10)
    period_to = models.CharField(verbose_name="Okres do", max_length=10)
    creator = models.ForeignKey(Employer, on_delete=models.CASCADE, verbose_name="Osoba wystawiająca",
                                related_name=relatedName)
    information = models.TextField("Informacje", blank=True, default="")
    creation_date = models.DateTimeField("Data utworzenia", auto_now_add=True)
    change_date = models.DateTimeField("Zmiana", auto_now=True)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, related_name=relatedName, verbose_name="Autor")

    def __str__(self):
        return f"Faktura nr {self.no_invoice} z dnia {self.date} na kwotę {self.sum} zł."


class InvoiceBuy(models.Model):
    class Meta:
        verbose_name = "Faktura - kupno"
        verbose_name_plural = "F.03 - Faktury - kupno"
        ordering = ["-date_receipt"]

    relatedName = "invoicebuy"

    date_receipt = models.DateField("Data wpływu")
    date_issue = models.DateField("Data wystawienia")
    no_invoice = models.CharField("Nr. faktury", max_length=30)
    doc_types = models.ForeignKey(DocumentTypes, null=False, blank=False, on_delete=models.CASCADE,
                                  verbose_name="Rodzaj dokumentu",
                                  related_name=relatedName)
    sum = models.DecimalField("Kwota [zł]", max_digits=10, decimal_places=2, null=True, blank=True)
    date_of_payment = models.DateField("Termin płatności")
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE, verbose_name="Kontrahent",
                                   related_name=relatedName)
    information = models.TextField("Informacje", blank=True, default="")
    creation_date = models.DateTimeField("Data utworzenia", auto_now_add=True)
    change_date = models.DateTimeField("Zmiana", auto_now=True)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, related_name=relatedName)

    def __str__(self):
        return f"{self.no_invoice} z dnia {self.date_issue.strftime('%d.%m.%Y')} r."


class InvoiceItems(models.Model):
    class Meta:
        verbose_name = "Element faktury"
        verbose_name_plural = "F.04 - Elementy faktury"
        ordering = ["invoice_id"]

    relatedName = "invoice_items"

    invoice_id = models.ForeignKey(InvoiceBuy, on_delete=models.CASCADE, verbose_name="Faktura",
                                   related_name=relatedName)
    account = models.ForeignKey(FinanceSource, on_delete=models.CASCADE, verbose_name="Konto",
                                related_name=relatedName)
    county = models.ForeignKey(County, on_delete=models.CASCADE, verbose_name="Powiat",
                               related_name=relatedName)
    sum = models.DecimalField("Kwota brutto [zł]", max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f"{self.account} - {self.county} - {self.sum} zł."


class CorrectiveNote(models.Model):
    class Meta:
        verbose_name = "Nota korygująca"
        verbose_name_plural = "F.02 - Noty korygujące"
        ordering = ["-date"]

    relatedName = "correctivenote"

    date = models.DateField("Data wystawienia")
    no_note = models.CharField("Nr. noty", max_length=15)
    contractor = models.ForeignKey(Contractor, on_delete=models.CASCADE, verbose_name="Kontrahent",
                                   related_name=relatedName)
    corrective_invoice = models.CharField("Korygowana faktura", max_length=70)
    information = models.TextField("Korygowana treść", blank=True, default="")
    creation_date = models.DateField("Data uworzenia", auto_now_add=True)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE, verbose_name="Autor",
                               related_name=relatedName)

    def __str__(self):
        return f"{self.no_note} z dnia {self.date}"

invoices/forms.py
from django.forms import ModelForm, DateInput, Textarea
from invoices.models import InvoiceSell, InvoiceBuy, InvoiceItems, CorrectiveNote


class DateField(DateInput):
    input_type = "date"


class MonthField(DateInput):
    input_type = "month"


class InvoiceSellForm(ModelForm):
    class Meta:
        model = InvoiceSell
        fields = "__all__"
        label = {'date': 'Data wystawienia', 'no_invoice': 'Nr. faktury', 'doc_types': 'Rodzaj dokumentu',
                 'contractor': 'Kontrahent', 'sum': 'Kwota',
                 'county': 'Powiat', 'date_of_payment': 'Termin płatności', 'period_from': 'Okres od',
                 'period_to': 'Okres do', 'creator': 'Osoba wystawiająca', 'information': 'Informacje',
                 'creation_date': 'Data utworzenia', 'change_date': 'Zmiana', 'author': 'Autor'}
        exclude = ['creation_date', 'change_date', 'author']
        widgets = {
            'date': DateField(),
            'period_from': MonthField(),
            'period_to': MonthField(),
            'date_of_payment': DateField(),
            'information': Textarea(attrs={'rows': 4})
        }


class InvoiceBuyForm(ModelForm):
    class Meta:
        model = InvoiceBuy
        fields = "__all__"
        label = {'date_receipt': 'Data wpływu', 'date_issue': 'Data wystawienia', 'no_invoice': 'Nr. faktury',
                 'doc_types': 'Rodzaj dokumentu', 'sum': 'Kwota', 'date_of_payment': 'Termin płatności',
                 'contractor': 'Kontrahent', 'information': 'Informacje'}
        exclude = ['creation_date', 'change_date', 'author']
        widgets = {
            'date_receipt': DateField(),
            'date_issue': DateField(),
            'date_of_payment': DateField(),
            'information': Textarea(attrs={'rows': 3})
        }


class InvoiceItemsForm(ModelForm):
    class Meta:
        model = InvoiceItems
        fields = ["account", "county", "sum"]
        label = {"account": "Konto", "county": "Powiat", "sum": "Kwota"}


class CorrectiveNoteForm(ModelForm):
    class Meta:
        model = CorrectiveNote
        fields = '__all__'
        label = {'date': 'Data wystawienia', 'no_note': 'Nr. noty', 'contractor': 'Kontrahent',
                 'corrective_invoice': 'Korygowana faktura', 'information': 'Korygowana treść'}
        exclude = ['creation_date', 'author']
        widgets = {'date': DateField()}

invoices/templates/invoices/form_corrective_note_archive.html
{%extends 'base.html'%}
{%load static%}
{%load bootstrap%}
{%block title%}{%if new%}Nowa Nota księgowa{%else%}Edycja Noty księgowej{%endif%}{%endblock%}

{%block content%}
<div class="row">
    <div class="col-md-3"><a href="{%url 'invoices:corrective_note_list_archive' year%}">
        <button class="btn btn-outline-primary my-btn"><span class="bi bi-chevron-compact-left">Cofnij</span></button>
    </a></div>
    <div class="col-md-6"><h4 class="text-center">{%if new%}Nowa Nota księgowa{%else%}Edycja Noty księgowej{%endif%}</h4></div>
</div>

<div class="container px-5 pb-5 col-md-7">
    <form method="post">
        {%csrf_token%}
        <div class="row">
            <div class="col-md-4 p-2">{{note_form.date|bootstrap}}</div>
            <div class="col-md-4 p-2">{{note_form.no_note|bootstrap}}</div>
            <div class="col-md-4 p-2">{{note_form.corrective_invoice|bootstrap}}</div>
            <div class="col-md-12 p-2">{{note_form.contractor|bootstrap}}</div>
            <div class="col-md-12 p-2">{{note_form.information|bootstrap}}</div>
            <div class="col-md-12 p-2 mt-2 moj-button-right">
                <button type="submit" class="btn btn-outline-primary my-btn">
                    <span class="bi bi-save2"> Zapisz zmiany</span>
                </button>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function(){
        $("#id_contractor").select2({placeholder:'Wybierz kontrahenta'});
    })
</script>
{%endblock%}

invoices/templates/invoices/form_invoice_items.html
{%extends 'base.html'%}
{%load static%}
{%load bootstrap%}
{%block title%}{%if new%}Nowa faktura{%else%}Edycja faktury{%endif%}{%endblock%}
{%block content%}
<div class="container col-md-7 mb-3">
    <div class="row">
        <div class="col-md-3 moj-button-left">
            <a href="{%url 'invoices:edit_invoice_buy' invoice.id %}">
                <button class="btn btn-outline-primary my-btn ">
                    <span class="bi bi-chevron-compact-left">Cofnij</span>
                </button>
            </a>
        </div>
        <div class="col-md-6">
            <h4 class="text-center">{%if new%} {{invoice.doc_types}}&nbsp;nr. {{invoice.no_invoice}} z dnia
                {{invoice.date_issue|date:"d.m.Y"}}&nbsp;r.{%else%}Edycja faktury{%endif%}</h4>
        </div>
        <div class="col-md-3 moj-button-right">
            <a href="{%url 'invoices:buy_invoices_list' %}">
                <button class="btn btn-outline-primary my-btn">
                    <span>Zapisz <i class="bi bi-chevron-compact-right"></i></span>
                </button>
            </a>
        </div>
    </div>
    <div class="container mt-5">
        <div class="row">
            <div class="p-1">
                <span class="text-muted">Kontahent: </span>
                <span>{{invoice.contractor}}</span><br>
                <span class="text-muted">Data płanotści: </span>
                <span><b>{{invoice.date_of_payment|date:"d.m.Y"}}&nbsp;r.</b></span><br>
                <span class="text-muted">Kwota faktury: </span>
                <span><b>{% if invoice.sum != None%}{{invoice.sum}} {%else%}0{%endif%}&nbsp;zł.</b></span><br>
                {%if invoice.information%}
                <p class="my-3">{{invoice.information}}</p>
                {%endif%}
            </div>
        </div>
    </div>
    <form class="mt-3" method="POST">
        {%csrf_token%}
        <div class="row">
            <div class="col-md-4">
                {{invoice_item.account|bootstrap}}
            </div>
            <div class="col-md-3">
                {{invoice_item.county|bootstrap}}
            </div>
            <div class="col-md-3">
                {{invoice_item.sum|bootstrap}}
            </div>
            <div class="col-md-2 mt-4 moj-button-right">
                <button type="submit" class="btn btn-outline-primary my-btn">
                    <span class="bi bi-save2"> Dodaj</span>
                </button>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col mt-5">
            <h5>Elementy faktury</h5>
            <table class="table table-hover my-table">
                <thead>
                <tr class="text-center">
                    <th><span>Rozdział</span></th>
                    <th><span>Grupa</span></th>
                    <th><span>Paragraf</span></th>
                    <th><span>Źródło finansowania</span></th>
                    <th><span>Jednostka</span></th>
                    <th><span>Kwota</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {%for item in invoice_items%}
                <tr>
                    <td align="center" valign="middle">
                        <span>{{item.account.section.section}}</span>
                    </td>
                    <td align="center" valign="middle">
                        <span>{{item.account.group}}</span>
                    </td>
                    <td align="center" valign="middle">
                        <span>{{item.account.paragraph}}</span>
                    </td>
                    <td align="center" valign="middle">
                        <span>{{item.account.source}}</span>
                    </td>
                    <td align="center" valign="middle">
                        <span>{{item.county}}</span>
                    </td>
                    <td align="center" valign="middle">
                        <span>{{item.sum}}</span>
                    </td>
                    <td align="center" valign="middle">
                        <a href="{%url 'invoices:delete_items_invoice_buy' item.id invoice.id%}">
                            <button class="btn btn-outline-danger mx-1" data-toggle="info" title="Usuń element">
                                <i class="bi bi-trash"></i>
                            </button>
                        </a>
                    </td>
                </tr>
                {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    document.getElementById("button-units").classList.remove("active");
    document.getElementById("button-record").classList.add("active");
    document.getElementById("button-cpv").classList.remove("active");
    document.getElementById("button-investments").classList.remove("active");

    $(document).ready(function(){
        $("#id_account").select2({placeholder:'Wybierz konto'});
    })
</script>
{%endblock%}

invoices/templates/invoices/main_invoice.html
{%extends 'base.html'%}
{%load static%}
{%block title%}Faktury{%endblock%}
{%block content%}
{%if user.is_authenticated and user.accessmodule.invoices_module%}
<div>
    <h2 class="text-center mb-5">Ewidencje faktur</h2>
</div>
<div class="container mt-3 ">
    <div class="container row d-flex justify-content-around">
        <div class="col-md-4">
            <section class="container my-div-style py-5">
                <div class="chose-invoices mb-5">
                    <a href="{%url 'invoices:sell_invoices_list'%}"><button type="button" class="btn btn-outline-primary button-chose-invoices my-btn">Sprzedaż<br>(rok: {{now_year}})</button></a>
                </div>
                <div class="text-center">
                    {%for year in all_year_sell%}
                    <a href="{%url 'invoices:sell_invoices_list_archive' year %}"><button type="button" class="btn btn-outline-dark m-2" data-toggle="info" title="Rok wystawienia">{{year}}</button></a>
                    {%endfor%}
                </div>
            </section>
        </div>
        <div class="col-md-4">
            <section class="container my-div-style py-5">
            <div class="chose-invoices mb-5">
                <a href="{%url 'invoices:corrective_note_list'%}"><button type="button" class="btn btn-outline-primary button-chose-invoices my-btn">Noty księgowe<br>(rok: {{now_year}})</button></a>
            </div>
            <div class="text-center">
                {% for year in year_note_list%}
                <a href="{%url 'invoices:corrective_note_list_archive' year%}"><button type="button" name="year_buy" class="btn btn-outline-dark m-2" data-toggle="info" title="Rok wystawienia">{{year}}</button></a>
                {%endfor%}
            </div>
           </section>
        </div>
        <div class="col-md-4">
            <section class="container my-div-style py-5">
            <div class="chose-invoices mb-5">
                <a href="{%url 'invoices:buy_invoices_list'%}"><button type="button" class="btn btn-outline-primary button-chose-invoices my-btn">Wydatki - gr.6<br>(rok: {{now_year}})</button></a>
            </div>
            <div class="text-center">
                {% for year in all_year_buy%}
                <a href="{%url 'invoices:buy_invoices_list_archive' year%}"><button type="button" name="year_buy" class="btn btn-outline-dark m-2" data-toggle="info" title="Rok wpływu">{{year}}</button></a>
                {%endfor%}
            </div>
           </section>
        </div>
    </div>
</div>
<script>
    document.getElementById("button-units").classList.remove("active");
    document.getElementById("button-record").classList.add("active");
    document.getElementById("button-secretariat").classList.remove("active");
    document.getElementById("button-cpv").classList.remove("active");
    document.getElementById("button-investments").classList.remove("active");
</script>
{%endif%}
{%endblock%}

invoices/templates/invoices/menu_invoice.html
{%extends 'base.html'%}
{%load static%}
{%block title%}Faktury{%endblock%}
{%block content%}
{%if user.is_authenticated and user.accessmodule.invoices_module%}
<div>
    <h2 class="text-center mb-5">Ewidencje faktur</h2>
</div>
<div class="container mt-3 ">
    <div class="container row d-flex justify-content-around">
        <div class="col-md-4">
            <section class="container my-div-style py-5">
                <div class="chose-invoices mb-5">
                    <a href="{%url 'invoices:sell_invoices_list'%}"><button type="button" class="btn btn-outline-primary button-chose-invoices my-btn">Sprzedaż<br>(rok: {{now_year}})</button></a>
                </div>
                <div class="text-center">
                    {%for year in all_year_sell%}
                    <a href="{%url 'invoices:sell_invoices_list_archive' year %}"><button type="button" class="btn btn-outline-dark m-2" data-toggle="info" title="Rok wystawienia">{{year}}</button></a>
                    {%endfor%}
                </div>
            </section>
        </div>
        <div class="col-md-4">
            <section class="container my-div-style py-5">
            <div class="chose-invoices mb-5">
                <a href="{%url 'invoices:corrective_note_list'%}"><button type="button" class="btn btn-outline-primary button-chose-invoices my-btn">Noty księgowe<br>(rok: {{now_year}})</button></a>
            </div>
            <div class="text-center">
                {% for year in year_note_list%}
                <a href="{%url 'invoices:corrective_note_list_archive' year%}"><button type="button" name="year_buy" class="btn btn-outline-dark m-2" data-toggle="info" title="Rok wystawienia">{{year}}</button></a>
                {%endfor%}
            </div>
           </section>
        </div>
        <div class="col-md-4">
            <section class="container my-div-style py-5">
            <div class="chose-invoices mb-5">
                <a href="{%url 'invoices:buy_invoices_list'%}"><button type="button" class="btn btn-outline-primary button-chose-invoices my-btn">Wydatki - gr.6<br>(rok: {{now_year}})</button></a>
            </div>
            <div class="text-center">
                {% for year in all_year_buy%}
                <a href="{%url 'invoices:buy_invoices_list_archive' year%}"><button type="button" name="year_buy" class="btn btn-outline-dark m-2" data-toggle="info" title="Rok wpływu">{{year}}</button></a>
                {%endfor%}
            </div>
           </section>
        </div>
    </div>
</div>
<script>
    document.getElementById("button-units").classList.remove("active");
    document.getElementById("button-record").classList.add("active");
    document.getElementById("button-secretariat").classList.remove("active");
    document.getElementById("button-cpv").classList.remove("active");
    document.getElementById("button-investments").classList.remove("active");
</script>
{%endif%}
{%endblock%}