WIiR_APP/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/doc/', include('django.contrib.admindocs.urls')),
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('units/', include('units.urls')),
                  path('investments/', include('investments.urls')),
                  path('contracts/', include('contracts.urls')),
                  path('contractors/', include('contractors.urls')),
                  path('invoices/', include('invoices.urls')),
                  path('permanentManagement/', include('permanentmanagement.urls')),
                  path('genre/', include('cpvdict.urls')),
                  path('donations/', include('donations.urls')),
                  path('inspections/', include('constructioninspections.urls')),
                  path('fixedAsset/', include('fixedasset.urls')),
                  path('operationalNeeds/', include('operationalneedsrecords.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('businessFlats/', include('businessflats.urls')),
                  path('login/', auth_views.LoginView.as_view(), name='login'),
                  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path('', include('main.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cpvdict/urls.py
from django.urls import path, re_path
from cpvdict.views import CpvDictionary, GenericMenu, OrderListView, ShowOrderInfo, NewOrderView, ConstructionWorksClassificationListView, \
    ShowInfoWorkObject, EditOrderView, ArchiveYearListView, OrderArchiveListView, \
    ConstructionWorksArchiveList, GenreArchiveView

app_name = 'cpvdict'
urlpatterns = [
    path('dictCPV/', CpvDictionary.as_view(), name='cpvlist'),
    path('genreTree/', GenericMenu.as_view(), name='type_expense_list'),
    path('buildingWorks/', ConstructionWorksClassificationListView.as_view(), name='type_work_list'),
    re_path('info/(?P<id>\d+)>/(?P<year>[0-9]{4})/$', ShowInfoWorkObject.as_view(), name='show_information_work_object'),
    path('orderList/', OrderListView.as_view(), name='order_list'),
    re_path('info/(?P<id>\d+)/$', ShowOrderInfo.as_view(), name='show_order_info_popup'),
    path('new_order/', NewOrderView.as_view(), name='new_order'),
    re_path('editOrder/(?P<id>\d+)/$', EditOrderView.as_view(), name='edit_order'),
    path('archiveListYear/', ArchiveYearListView.as_view(), name='make_archive_year_list'),
    re_path('archiveListOrder/(?P<year>\d+)/$', OrderArchiveListView.as_view(), name='create_order_archive'),
    re_path('archiveBuildingWorks/(?P<year>\d+)/$', ConstructionWorksArchiveList.as_view(), name='create_type_work_list_archive'),
    re_path('genreTreeArchive/(?P<year>\d+)/$', GenreArchiveView.as_view(), name='create_genre_archive')
]

fixedasset/urls.py
from django.urls import path, re_path
from fixedasset.views import FixedAssetListView, ShowInformationView, AddBuildingView, EditBuildingView

app_name = "fixedasset"

urlpatterns = [
    path("buildings/", FixedAssetListView.as_view(), name="fixed_asset_list"),
    re_path("buildings/info/(?P<id>\d+)/$", ShowInformationView.as_view(), name="show_information"),
    path("buildings/add/", AddBuildingView.as_view(), name="add_new_building"),
    re_path("buildings/edit/(?P<id>\d+)/$", EditBuildingView.as_view(), name="edit_building")
]

gallery/urls.py
from django.urls import path, re_path
from gallery.views import GalleryDetailsView, GalleryListView, AddGallery, NewGalleryDetails

app_name = 'gallery'

urlpatterns = [
    path('all/', GalleryListView.as_view(), name='gallery_list'),
    path('new/', AddGallery.as_view(), name='add_gallery'),
    re_path('details/(?P<gallery_id>\d+)/$', GalleryDetailsView.as_view(), name='gallery_details'),
    re_path('(?P<gallery_id>\d+)/$', NewGalleryDetails.as_view(), name='new_gallery_details')
]

main/urls.py
from django.urls import path, re_path
from main.views import ListRegisterView, WelcomeView, SecretariatSiteView, EmployersListView, CommandListView, \
    AccessToModulesView, TelephoneListView, ShowTeamsListView, NewTeamView, EditTeamView, \
    NewEmployerView, EditEmployerView, AddCommandView, EditCommandView, DeleteCommandView, \
    NewSecretariatNumberView, EditSecretariatNumberView, DeleteSecretariatNumberView, EditRentCarView, DeleteRentCar, \
    NewRentCatView, NecesseryFileView, DownloadFilesView, AddUploadFilesView, DeleteUploadFile

app_name = 'main'
urlpatterns = [
    path('secretariat/', SecretariatSiteView.as_view(), name='make_secretariat_site'),
    path('addRentCar/', NewRentCatView.as_view(), name='add_rent_car'),
    re_path('rentCar/(?P<id>\d+)/$', EditRentCarView.as_view(), name='edit_rent_car'),
    re_path('deleteRentCar/(?P<id>\d+)/$', DeleteRentCar.as_view(), name='delete_rent_car'),
    path('addSecretariatInfo/', NewSecretariatNumberView.as_view(), name='add_secretariat_number'),
    re_path('editSecretariatInfo/(?P<id>\d+)/$', EditSecretariatNumberView.as_view(), name='edit_secretariat_number'),
    re_path('delete_secretariat/(?P<id>\d+)/$', DeleteSecretariatNumberView.as_view(),
            name='delete_secretariat_number'),
    path('secretariat/teams/', ShowTeamsListView.as_view(), name='show_teams_list'),
    path('secretariat/teams/add/', NewTeamView.as_view(), name='add_team_popup'),
    re_path('secretariat/teams/edit/(?P<id>\d+)/$', EditTeamView.as_view(), name='edit_team_popup'),
    path('secretariat/employers/', EmployersListView.as_view(), name='show_employers_list'),
    path('secretariat/employers/add/', NewEmployerView.as_view(), name='add_employer_popup'),
    re_path('secretariat/employers/edit/(?P<id>\d+)/$', EditEmployerView.as_view(), name='edit_employer_popup'),
    path('secretariat/commands/', CommandListView.as_view(), name='show_command_list'),
    path('secretariat/commands/add/', AddCommandView.as_view(), name='add_command_popup'),
    re_path('secretariat/commands/edit/(?P<id>\d+)/$', EditCommandView.as_view(), name='edit_command_popup'),
    re_path('secretariat/commands/delete/(?P<id>\d+)/$', DeleteCommandView.as_view(), name='delete_command_popup'),
    path('access/', AccessToModulesView.as_view(), name='give_access_to_modules'),
    path('registerList/', ListRegisterView.as_view(), name='make_list_register'),
    path('telephones/', TelephoneListView.as_view(), name='telephone_list'),
    path('files/', NecesseryFileView.as_view(), name='files'),
    path('secretariat/upload_files/', DownloadFilesView.as_view(), name='download_files'),
    path('secretariat/upload_files/add/', AddUploadFilesView.as_view(), name='add_download_files_popup'),
    re_path('secretariat/upload_file/delete/(?P<id>\d+)/$', DeleteUploadFile.as_view(), name='delete_download_file'),
    path('', WelcomeView.as_view(), name='welcome')

]

units/urls.py
from django.urls import path, re_path
from .views import UnitListView, AddUnitView, UnitsArchiveListView, UnitsEditableListView, EditUnitView, ShowAllInfoUnit

app_name = "units"
urlpatterns = [
    path("list/", UnitsEditableListView.as_view(), name="create_units_list_editable"),
    path("list/new/", AddUnitView.as_view(), name="add_unit"),
    re_path("list/edit/(?P<slug>[\w-]+)/$", EditUnitView.as_view(), name="edit_unit"),
    path("list/archive/", UnitsArchiveListView.as_view(), name="archive_units_list"),
    re_path("info/(?P<slug>[\w-]+)/$", ShowAllInfoUnit.as_view(), name="show_all_info_unit"),
    path("", UnitListView.as_view(), name="units_list")
]

main/models.py
from django.db import models
from enum import Enum
import os


# Create your models here.
class Team(models.Model):
    class Meta:
        verbose_name = "Komórka Wydziału"
        verbose_name_plural = "S.02 - Komórki Wydziału"
        ordering = ["priority"]

    priority = models.IntegerField("Priorytet", null=True, blank=True, default=0)
    team = models.CharField(max_length=50, verbose_name="Komórka Wydziału")
    active = models.BooleanField("Aktywny", default=True)

    def __str__(self):
        return f"{self.team}"


class TeamEnum(Enum):
    NK = [1, "Naczelnicy"]
    ZOK = [2, "Zespół Kancelaryjny"]
    ZRIWT = [3, "Zespół Rozliczen i Wsparcia technicznego"]
    ZI = [4, "Zespół Inwestychi"]
    ZE = [5, "Zespół Eksploatacji"]
    ZM = [6, "Zespół Mieszkaniowy"]
    ZN = [7, "Zespół Nieruchomości"]


class SecretariatTelephone(models.Model):
    class Meta:
        verbose_name = "Telefon do sekretariatu"
        verbose_name_plural = "S.05 - Telefony do sekretariatu"

    code = models.IntegerField("Nr. kierunkowy", null=True, blank=True)
    fax_number = models.CharField("Nr. faxu", max_length=6, null=True, blank=True, default="")
    secretariat_number = models.CharField("Nr. do sekretariatu", max_length=6, null=True, blank=True, default="")
    information = models.TextField("Informacje", null=True, blank=True)
    create = models.DateTimeField("Data utworzenia", auto_now_add=True)

    def __str__(self):
        return f"{self.code} {self.secretariat_number}"


class OrganisationTelephone(models.Model):
    class Meta:
        verbose_name = "Książka telefoniczna KWP w Poznaniu"
        verbose_name_plural = "S.06 - Książka telefoniczna KWP w Poznaniu"

    telephone_book = models.FileField(upload_to="KWP_telephone/%Y/", null=True,
                                      verbose_name="Spis telefonów KWP w Poznaniu")
    add_date = models.DateField("Data dodania", auto_now_add=True)


class IndustryType(models.Model):
    class Meta:
        verbose_name = "Branża"
        verbose_name_plural = "S.03 - Branże"

    industry = models.CharField("Brażna", max_length=50)

    def __str__(self):
        return f"{self.industry}"


class Employer(models.Model):
    class Meta:
        verbose_name = "Pracownik"
        verbose_name_plural = "S.04 - Pracownicy"
        ordering = ["team", "last_name"]

    related_name = "employer"

    id_swop = models.CharField(verbose_name="ID SWOP", max_length=6, unique=True)
    name = models.CharField(verbose_name="Imię", max_length=20)
    last_name = models.CharField(verbose_name="Nazwisko", max_length=25)
    position = models.CharField(verbose_name="Stanowisko", max_length=20, blank=True, default="")
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name="Zespół", related_name=related_name)
    industry_specialist = models.BooleanField(default=False, verbose_name="Branżysta")
    invoices_issues = models.BooleanField(default=False, verbose_name="Wystawianie faktur")
    industry = models.ForeignKey(IndustryType, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Branża",
                                 related_name=related_name)
    no_room = models.CharField(verbose_name="Nr. pokoju", max_length=2, blank=True, default="")
    no_tel_room = models.CharField(verbose_name="Nr. telefonu", max_length=6, blank=True, default="")
    no_tel_private = models.CharField(verbose_name="Nr. komórkowy", max_length=9, blank=True, default="")
    information = models.TextField(verbose_name="Informacje", max_length=200, null=True, blank=True)
    deleted = models.BooleanField(verbose_name="Usunięty", default=False)
    creation_date = models.DateTimeField(auto_now_add=True)
    change = models.DateTimeField(verbose_name="Data zmian", auto_now=True)
    author = models.ForeignKey(to="auth.User", on_delete=models.CASCADE, related_name="employer")

    def __str__(self):
        return f"{self.name} {self.last_name}"


class AccessModule(models.Model):
    relatedName = "accessmodule"

    class Meta:
        verbose_name = "Dostęp do modułów"
        verbose_name_plural = "S.01 - Dostęp do modułów"

    user = models.OneToOneField("auth.User", on_delete=models.CASCADE, verbose_name="Użytkownik",
                                related_name=relatedName)
    zok_team = models.BooleanField(verbose_name="Ewidencja: Zespoł Obsługi Kancelarynej", default=False)
    teams = models.BooleanField(verbose_name="ZOK - Zespoły", default=False)
    commands = models.BooleanField(verbose_name="ZOK - Polecenia", default=False)
    employers = models.BooleanField(verbose_name="ZOK - Pracownicy", default=False)
    cars = models.BooleanField(verbose_name="ZOK - Rezerwacja samochodu służbowego", default=False)
    zriwt_team = models.BooleanField(verbose_name="Ewidencja: Zespół Rozliczeń i Wsparcia Technicznego", default=False)
    contractors_module = models.BooleanField(verbose_name="ZRiWT - Kontrahenci - Podgląd", default=False)
    contractors_module_edit = models.BooleanField(verbose_name="ZRiWT - Kontrahenci - Edycja", default=False)
    invoices_module = models.BooleanField(verbose_name="ZRiWT - Faktury - Podgląd", default=False)
    invoices_module_edit = models.BooleanField(verbose_name="ZRiWT - Faktury - Edycja", default=False)
    donations_module = models.BooleanField(verbose_name="ZRiWT - Darowizny - Podgląd", default=False)
    donations_module_edit = models.BooleanField(verbose_name="ZRiWT - Darowizny - Edycja", default=False)
    buildings_module = models.BooleanField(verbose_name="ZRiWT - Środki trwałe - budynki - Podgląd", default=False)
    buildings_module_edit = models.BooleanField(verbose_name="ZRiWT - Środki trwałe - budynki - Edycja", default=False)
    inspections_module = models.BooleanField(verbose_name="ZRiWT - Przeglądy - Podgląd", default=False)
    inspections_module_edit = models.BooleanField(verbose_name="ZRiWT - Przeglądy - Edycja", default=False)
    contracts_auction_module = models.BooleanField(verbose_name="ZRiWT - Umowy ZZP - Podgląd", default=False)
    contracts_auction_module_edit = models.BooleanField(verbose_name="ZRiWT - Umowy ZZP - Edycja", default=False)
    investments_module = models.BooleanField(verbose_name="ZRiWT - Inwestycje - Podgląd", default=False)
    investments_module_edit = models.BooleanField(verbose_name="ZRiWT - Inwestycje - Edycja", default=False)
    cpvdict_module = models.BooleanField(verbose_name="ZRiWT - Rodzajowość - Podgląd", default=False)
    cpvdict_module_edit = models.BooleanField(verbose_name="ZRiWT - Rodzajowość - Edycja", default=False)
    gallery_module = models.BooleanField(verbose_name="ZRiWT - Galeria - Podgląd", default=False)
    gallery_module_edit = models.BooleanField(verbose_name="ZRiWT - Galeria - Edycja", default=False)
    zm_team = models.BooleanField(verbose_name="Ewidencja: Zespół Mieszkaniowy", default=False)
    official_flat = models.BooleanField(verbose_name="ZM - Mieszkania służbowe - Podgląd", default=False)
    official_flat_edit = models.BooleanField(verbose_name="ZM - Mieszkania służbowe - Edycja", default=False)
    zn_team = models.BooleanField(verbose_name="Ewidencja: Zespół Nieruchomości", default=False)
    units = models.BooleanField(verbose_name="ZN - Jednostki - Podgląd", default=False)
    units_edit = models.BooleanField(verbose_name="ZN - Jednostki - Edycja", default=False)
    contract_immovables = models.BooleanField(verbose_name="ZN - Umowy nieruchomości - Podgląd", default=False)
    contract_immovables_edit = models.BooleanField(verbose_name="ZN - Umowy nieruchomości - Edycja", default=False)
    ze_team = models.BooleanField(verbose_name="Ewidencja: Zespół Eksploatacji", default=False)
    records_letters = models.BooleanField(verbose_name="ZE - Ewidencja Pism - Podgląd", default=False)
    records_letters_edit = models.BooleanField(verbose_name="ZE - Ewidencja Pism - Edycja", default=False)
    contract_media = models.BooleanField(verbose_name="ZE - Umowy Media - Podgląd", default=False)
    contract_media_edit = models.BooleanField(verbose_name="ZE - Umowy Media - Edycja", default=False)

    def __str__(self):
        return f"{self.user} - {self.user.first_name} {self.user.last_name}"


def upload_scan(instance, filename):
    extension = filename.split(".")[-1]
    title = instance.title
    new_title = title.replace(" ", "_")
    return f"commands/{new_title}.{extension}"


class Command(models.Model):
    class Meta:
        verbose_name = "Polecenie"
        verbose_name_plural = "S.07 - Polecenia"
        ordering = ["-create_date"]

    title = models.CharField("Nazwa", max_length=120)
    content = models.TextField("Treść")
    scan = models.FileField(upload_to=upload_scan, verbose_name="Skan polecenia")
    change = models.DateTimeField(verbose_name="Data zmian", auto_now=True)
    create_date = models.DateTimeField(verbose_name="Data dodania", auto_now_add=True)

    def __str__(self):
        return f"{self.title}"


class Car(models.Model):
    class Meta:
        verbose_name = "Samochód sużbowy"
        verbose_name_plural = "S.08 - Samochód służbowy"
        ordering = ["-rent_date"]

    related_name = "car"

    rent_date = models.DateField(verbose_name="Data", unique=True)
    borrower = models.ManyToManyField(Employer, verbose_name="Delegat", related_name=related_name)
    target = models.TextField("Cel")
    create_date = models.DateTimeField(verbose_name="Data utworzenia", auto_now_add=True)
    change = models.DateTimeField(verbose_name="Zmiana", auto_now=True)
    author = models.ForeignKey(to="auth.User", on_delete=models.CASCADE, related_name=related_name, verbose_name="Autor")

    def __str__(self):
        return f"{self.rent_date.strftime('%d.%m.%Y')} - {self.target}"


def upload_file(instance, filename):
    extension = filename.split(".")[-1]
    title = instance.title
    new_title = title.replace(" ", "_")
    return f'shared_file/{new_title}.{extension}'


class NecesseryFile(models.Model):

main/templates/main/download_file_form_popup.html
{%load static%}
{%load bootstrap%}
{%block content%}
{%if user.is_authenticated and user.accessmodule.zok_team%}
<div class="container">
    <form class="col m-2 p-4" method="POST" enctype="multipart/form-data" action="{%url 'main:add_download_files_popup'%}">
        {%csrf_token%}
        <div class="row">
            <div class="col-md-12 mt-3">{{download_file_form.title|bootstrap}}</div>
            <div class="col-md-6 mt-3">{{download_file_form.file|bootstrap}}</div>
        </div>
        <div class="mt-4 moj-button-right">
            <button type="submit" class="btn btn-outline-primary my-btn">
                <span class="bi bi-save2"> Dodaj</span>
            </button>
        </div>
    </form>
</div>
{%endif%}
{%endblock%}

main/templates/main/employers_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} SEKRETARIAT {% endblock %}
{% block content %}
{%if user.is_authenticated and user.accessmodule.zok_team%}
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <a href="{%url 'main:make_secretariat_site'%}">
                <button class="btn btn-outline-primary my-btn">
                    <span class="bi bi-chevron-compact-left">Cofnij</span>
                </button>
            </a>
        </div>
        <div class="col-md-8 text-center">
            <h5>Pracownicy Wydziału</h5>
            {%if last_date%}
            <small>Ostatnia aktualizacja: {{last_date.change|date:'m.d.Y (H:i)'}}</small>
            {%endif%}
        </div>
        <div class="col-md-2 moj-button-right">
            {%if secretariat%}
            <button class="btn btn-outline-primary my-btn" type="button" data-toggle="info" onclick="openModalEditSecretariat()" title="Edytuj numery sekretariatu">
                <span class="bi bi-telephone h4"></span>
            </button>
            {%else%}
            <button class="btn btn-outline-primary my-btn" type="button" data-toggle="info" onclick="openModalAddSecretariat()" title="Dodaj numery sekretariatu">
                <span class="bi bi-telephone h4"></span>
            </button>
            {%endif%}
            <button class="btn btn-outline-primary my-btn" type="button" data-toggle="info" onclick="openModalEmployerAdd()" title="Dodaj nowego pracownika">
                <span class="bi bi-person-plus h4"></span>
            </button>
        </div>
        {%if secretariat%}
         <div>
             {%if secretariat.code%}
             <span class="text-muted">Nr. kierunkowy:</span>&nbsp;<span>{{secretariat.code}}</span><br>
             {%endif%}
             {%if secretariat.secretariat_number%}
             <span class="text-muted">Nr. do sekretariatu:</span>&nbsp;<span>{{secretariat.secretariat_number}}</span><br>
             {%endif%}
             {%if secretariat.fax_number%}
             <span class="text-muted">Nr. Fax do WIiR:</span>&nbsp;<span>{{secretariat.fax_number}}</span><br>
             {%endif%}
             {%if secretariat.information%}
             <span class="text-muted" data-toggle="info" title="Informacja ukazująca się w spisie telefonów">Informacja:</span>&nbsp;<span>{{secretariat.information}}</span><br>
             {%endif%}
        </div>
        {%endif%}
    </div>
    <div class="row mt-4">
        <table class="table table-sm">
            <thead class="table-dark">
            <tr class="my-table-tr">
                <th align="center" valign="middle" width="60px" scope="col" class="text-center">L.p.</th>
                <th align="center" valign="middle" width="120" scope="col">Stanowisko</th>
                <th align="center" valign="middle" width="220" scope="col">Imię i nazwisko</th>
                <th align="center" valign="middle" width="220" scope="col" class="text-center">Zespół</th>
                <th align="center" valign="middle" width="250" scope="col" class="text-center">Branża</th>
                <th align="center" valign="middle" width="10" scope="col" class="text-center">Nr.pokoju</th>
                <th align="center" valign="middle" width="100" scope="col" class="text-center">Nr.tel</th>
                <th align="center" valign="middle" width="120" scope="col" class="text-center">Nr.komórkowy</th>
                <th colspan="3" align="center" valign="middle" width="" scope="col" class="text-center"></th>
            </tr>
            </thead>
            <tbody>
            {%for employer in employers%}
            <tr class="my-table-tr">
                <td align="center" valign="middle" class="text-center" scope="row" width=""></td>
                <td align="left" valign="middle">{{employer.position}}</td>
                <td align="left" valign="middle"><span data-toggle="info" title="{{employer.id_swop}}">{{employer.name}} {{employer.last_name}}</span></td>
                <td align="center" valign="middle">{{employer.team}}</td>
                {%if employer.industry%}
                <td align="center" valign="middle">
                    <span>{{employer.industry}}</span>
                    {%if employer.industry_specialist%}
                    <span data-toggle="info" title="Branżysta merytoryczny" class="bi bi-hammer"></span>
                    {%else%}
                    <span data-toggle="info" title="Branżysta finansowy" class="bi bi-cash-coin"></span>
                    {%endif%}
                </td>
                {%else%}
                <td align="center" valign="middle">---</td>
                {%endif%}
                <td align="center" valign="middle">{{employer.no_room}}</td>
                <td align="center" valign="middle">{{employer.no_tel_room}}</td>
                <td align="center" valign="middle">{{employer.no_tel_private}}</td>
                <td data-toggle="info" align="center" valign="middle" title="Edytuj">
                    <button class="btn btn-outline" data-url="{% url 'main:edit_employer_popup' employer.id %}" onclick="openModalEmployerEdit(this)">
                        <i class="bi bi-pencil-square"></i>
                    </button>
                </td>
            </tr>
            {%endfor%}
            </tbody>
        </table>
    </div>
</div>
<!-- Modal -->
<div class="modal fade modal-style" id="addSecretariatModal" data-url="{%url 'main:add_secretariat_number'%}">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
{%if secretariat%}
<div class="modal fade modal-style" id="editSecretariatModal" data-url="{%url 'main:edit_secretariat_number' secretariat.id%}">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
{%endif%}
<div class="modal fade modal-style" id="addEmployerModal"  data-url="{%url 'main:add_employer_popup'%}">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
<div class="modal fade" id="editEmployerModal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
<script>
    document.getElementById("button-units").classList.remove("active");
    document.getElementById("button-record").classList.remove("active");
    document.getElementById("button-secretariat").classList.add("active");
    document.getElementById("button-cpv").classList.remove("active");
    document.getElementById("button-investments").classList.remove("active");

    function openModalAddSecretariat(){
        var url = $("#addSecretariatModal").data("url");
        $("#addSecretariatModal .modal-content").load(url);
        $("#addSecretariatModal").modal("show");
    }

    function openModalEditSecretariat(){
        var url = $("#editSecretariatModal").data("url");
        $("#editSecretariatModal .modal-content").load(url);
        $("#editSecretariatModal").modal("show");
    }

    function openModalEmployerAdd(){
        var url = $("#addEmployerModal").data("url");
        $("#addEmployerModal .modal-content").load(url);
        $("#addEmployerModal").modal("show");
    }

    function openModalEmployerEdit(button){
        var url = $(button).data("url");
        $("#editEmployerModal .modal-content").load(url);
        $("#editEmployerModal").modal("show");
        }

    function submitForm(){
        $("#submitButton").closest("form").submit();
    }

</script>
{%endif%}
{% endblock %}

main/templates/main/secretariat_menu.html
{% extends 'base.html' %}
{% load static %}
{% block title %} SEKRETARIAT {% endblock %}
{% block content %}
{%if user.is_authenticated and user.accessmodule.zok_team%}
<div class="container">
    <h5 class="text-center mb-4">
        <span>Sekretariat</span>
    </h5>
    <div class="d-flex justify-content-center pt-2">
        <div class="col-md-4 text-center">
            <ul class="list-group">
                {%if user.accessmodule.teams%}
                <li class="list-group my-2">
                    <a class="d-block btn btn-outline-primary my-btn" href="{%url 'main:show_teams_list'%}">Struktura Wydziału</a>
                </li>
                {%endif%}

                {%if user.accessmodule.employers%}
                <li class="list-group my-2">
                    <a class="d-block btn btn-outline-primary my-btn" href="{%url 'main:show_employers_list'%}">Pracownicy</a>
                </li>
                {%endif%}

                {%if user.accessmodule.commands%}
                <li class="list-group my-2">
                    <a class="d-block btn btn-outline-primary my-btn" href="{%url 'main:show_command_list'%}">Polecenia Naczelnika</a>
                </li>
                <li class="list-group my-2">
                    <a class="d-block btn btn-outline-primary my-btn" href="{%url 'main:download_files'%}">Pliki</a>
                </li>
                {%endif%}
            </ul>
        </div>
    </div>
</div>

<script>
    document.getElementById("button-units").classList.remove("active");
    document.getElementById("button-record").classList.remove("active");
    document.getElementById("button-secretariat").classList.add("active");
    document.getElementById("button-cpv").classList.remove("active");
    document.getElementById("button-investments").classList.remove("active");
    function openModal(button){
        var url = $(button).data("url");
        $("#orderInformationModal .modal-content").load(url);
        $("#orderInformationModal").modal("show");
    }
    function submitForm(){
        $("#submitButton").closest("form").submit();
    }
</script>
{%endif%}
{% endblock %}