WIiR_APP/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('admin/doc/', include('django.contrib.admindocs.urls')),
                  path('admin/', admin.site.urls),
                  path('tinymce/', include('tinymce.urls')),
                  path('units/', include('units.urls')),
                  path('investments/', include('investments.urls')),
                  path('contracts/', include('contracts.urls')),
                  path('contractors/', include('contractors.urls')),
                  path('invoices/', include('invoices.urls')),
                  path('permanentManagement/', include('permanentmanagement.urls')),
                  path('genre/', include('cpvdict.urls')),
                  path('donations/', include('donations.urls')),
                  path('inspections/', include('constructioninspections.urls')),
                  path('fixedAsset/', include('fixedasset.urls')),
                  path('operationalNeeds/', include('operationalneedsrecords.urls')),
                  path('gallery/', include('gallery.urls')),
                  path('businessFlats/', include('businessflats.urls')),
                  path('login/', auth_views.LoginView.as_view(), name='login'),
                  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path('', include('main.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cpvdict/urls.py
from django.urls import path, re_path
from cpvdict.views import CpvDictionary, GenericMenu, OrderListView, ShowOrderInfo, NewOrderView, ConstructionWorksClassificationListView, \
    ShowInfoWorkObject, EditOrderView, ArchiveYearListView, OrderArchiveListView, \
    ConstructionWorksArchiveList, GenreArchiveView

app_name = 'cpvdict'
urlpatterns = [
    path('dictCPV/', CpvDictionary.as_view(), name='cpvlist'),
    path('genreTree/', GenericMenu.as_view(), name='type_expense_list'),
    path('buildingWorks/', ConstructionWorksClassificationListView.as_view(), name='type_work_list'),
    re_path('info/(?P<id>\d+)>/(?P<year>[0-9]{4})/$', ShowInfoWorkObject.as_view(), name='show_information_work_object'),
    path('orderList/', OrderListView.as_view(), name='order_list'),
    re_path('info/(?P<id>\d+)/$', ShowOrderInfo.as_view(), name='show_order_info_popup'),
    path('new_order/', NewOrderView.as_view(), name='new_order'),
    re_path('editOrder/(?P<id>\d+)/$', EditOrderView.as_view(), name='edit_order'),
    path('archiveListYear/', ArchiveYearListView.as_view(), name='make_archive_year_list'),
    re_path('archiveListOrder/(?P<year>\d+)/$', OrderArchiveListView.as_view(), name='create_order_archive'),
    re_path('archiveBuildingWorks/(?P<year>\d+)/$', ConstructionWorksArchiveList.as_view(), name='create_type_work_list_archive'),
    re_path('genreTreeArchive/(?P<year>\d+)/$', GenreArchiveView.as_view(), name='create_genre_archive')
]

investments/urls.py
from django.urls import path, re_path
from investments.views import ImportantTaskInvestments, InvestmentProjectsList, AddProjectView, EditProjectView, \
    ShowProjectView, ShowGalleriesView, AddContractToProject

app_name = "investments"
urlpatterns = [
    path("menu/list/", InvestmentProjectsList.as_view(), name="investment_projects_list"),
    path("menu/list/new/", AddProjectView.as_view(), name="add_new_project"),
    re_path("menu/list/edit/(?P<id>\d+)/$", EditProjectView.as_view(), name="edit_project"),
    re_path("menu/list/show/(?P<id>\d+)/$", ShowProjectView.as_view(), name="show_project"),
    re_path("gallery/(?P<id>\d+)/$", ShowGalleriesView.as_view(), name="show_galleries_popup"),
    re_path("menu/list/addToProject/(?P<id>\d+)/$", AddContractToProject.as_view(), name="add_contract_to_project"),
    path("menu/", ImportantTaskInvestments.as_view(), name="make_important_task_investments")

]

main/urls.py
from django.urls import path, re_path
from main.views import ListRegisterView, WelcomeView, SecretariatSiteView, EmployersListView, CommandListView, \
    AccessToModulesView, TelephoneListView, ShowTeamsListView, NewTeamView, EditTeamView, \
    NewEmployerView, EditEmployerView, AddCommandView, EditCommandView, DeleteCommandView, \
    NewSecretariatNumberView, EditSecretariatNumberView, DeleteSecretariatNumberView, EditRentCarView, DeleteRentCar, \
    NewRentCatView, NecesseryFileView, DownloadFilesView, AddUploadFilesView, DeleteUploadFile

app_name = 'main'
urlpatterns = [
    path('secretariat/', SecretariatSiteView.as_view(), name='make_secretariat_site'),
    path('addRentCar/', NewRentCatView.as_view(), name='add_rent_car'),
    re_path('rentCar/(?P<id>\d+)/$', EditRentCarView.as_view(), name='edit_rent_car'),
    re_path('deleteRentCar/(?P<id>\d+)/$', DeleteRentCar.as_view(), name='delete_rent_car'),
    path('addSecretariatInfo/', NewSecretariatNumberView.as_view(), name='add_secretariat_number'),
    re_path('editSecretariatInfo/(?P<id>\d+)/$', EditSecretariatNumberView.as_view(), name='edit_secretariat_number'),
    re_path('delete_secretariat/(?P<id>\d+)/$', DeleteSecretariatNumberView.as_view(),
            name='delete_secretariat_number'),
    path('secretariat/teams/', ShowTeamsListView.as_view(), name='show_teams_list'),
    path('secretariat/teams/add/', NewTeamView.as_view(), name='add_team_popup'),
    re_path('secretariat/teams/edit/(?P<id>\d+)/$', EditTeamView.as_view(), name='edit_team_popup'),
    path('secretariat/employers/', EmployersListView.as_view(), name='show_employers_list'),
    path('secretariat/employers/add/', NewEmployerView.as_view(), name='add_employer_popup'),
    re_path('secretariat/employers/edit/(?P<id>\d+)/$', EditEmployerView.as_view(), name='edit_employer_popup'),
    path('secretariat/commands/', CommandListView.as_view(), name='show_command_list'),
    path('secretariat/commands/add/', AddCommandView.as_view(), name='add_command_popup'),
    re_path('secretariat/commands/edit/(?P<id>\d+)/$', EditCommandView.as_view(), name='edit_command_popup'),
    re_path('secretariat/commands/delete/(?P<id>\d+)/$', DeleteCommandView.as_view(), name='delete_command_popup'),
    path('access/', AccessToModulesView.as_view(), name='give_access_to_modules'),
    path('registerList/', ListRegisterView.as_view(), name='make_list_register'),
    path('telephones/', TelephoneListView.as_view(), name='telephone_list'),
    path('files/', NecesseryFileView.as_view(), name='files'),
    path('secretariat/upload_files/', DownloadFilesView.as_view(), name='download_files'),
    path('secretariat/upload_files/add/', AddUploadFilesView.as_view(), name='add_download_files_popup'),
    re_path('secretariat/upload_file/delete/(?P<id>\d+)/$', DeleteUploadFile.as_view(), name='delete_download_file'),
    path('', WelcomeView.as_view(), name='welcome')

]

units/urls.py
from django.urls import path, re_path
from .views import UnitListView, AddUnitView, UnitsArchiveListView, UnitsEditableListView, EditUnitView, ShowAllInfoUnit

app_name = "units"
urlpatterns = [
    path("list/", UnitsEditableListView.as_view(), name="create_units_list_editable"),
    path("list/new/", AddUnitView.as_view(), name="add_unit"),
    re_path("list/edit/(?P<slug>[\w-]+)/$", EditUnitView.as_view(), name="edit_unit"),
    path("list/archive/", UnitsArchiveListView.as_view(), name="archive_units_list"),
    re_path("info/(?P<slug>[\w-]+)/$", ShowAllInfoUnit.as_view(), name="show_all_info_unit"),
    path("", UnitListView.as_view(), name="units_list")
]

main/views.py
import logging
from django.shortcuts import render, get_object_or_404, redirect
import datetime
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from main.models import Team, OrganisationTelephone, AccessModule, Command, Employer, SecretariatTelephone, Car, \
    NecesseryFile
from main.forms import TeamForm, EmployerForm, CommandForm, SecretariatTelephoneForm, CarForm, NecesseryFileForm
from businessflats.models import OfficialFlat
from units.models import Unit
from contracts.models import ContractImmovables, ContractAuction, ContractMedia
from contractors.models import Contractor
from donations.models import Application
from gallery.models import Gallery
from investments.models import Project
from cpvdict.models import Genre
from invoices.models import InvoiceBuy, InvoiceSell, CorrectiveNote
from fixedasset.models import Building
from operationalneedsrecords.models import NeedsLetter

logger = logging.getLogger(__name__)


def current_year():
    return datetime.date.today().year


def now_date():
    return datetime.datetime.now()


class WelcomeView(LoginRequiredMixin, View):
    template = 'main/home.html'
    template_error = 'main/error_site.html'

    def get(self, request):
        try:
            commands = Command.objects.all().order_by("create_date")[:6]
            rent_cars = Car.objects.all()[:10]
            date = datetime.date.today().today()
            context = {"date": date,
                       "commands": commands,
                       "rent_cars": rent_cars}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)


class NewRentCatView(LoginRequiredMixin, View):
    template = 'main/car_form.html'
    template_error = 'main/error_site.html'
    form_class = CarForm

    def get(self, request):
        try:
            form = self.form_class()
            context = {'rent_car': form, 'new': True}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)

    def post(self, request):
        try:
            form = self.form_class(request.POST or None)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                form.save()
                return redirect('main:welcome')
            context = {'rent_car': form, 'new': True}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)


class EditRentCarView(LoginRequiredMixin, View):
    template = 'main/car_form.html'
    template_error = 'main/error_site.html'
    form_class = CarForm

    def get(self, request, id):
        try:
            car = get_object_or_404(Car, pk=id)
            form = self.form_class(instance=car)
            context = {'rent_car': form, 'id': id, 'new': False}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)

    def post(self, request, id):
        try:
            car = get_object_or_404(Car, pk=id)
            form = self.form_class(request.POST or None, instance=car)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                form.save()
                return redirect("main:welcome")
            context = {'rent_car': form, 'id': id, 'new': False}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)


class DeleteRentCar(LoginRequiredMixin, View):
    def get(self, request, id):
        try:
            rent_car = get_object_or_404(Car, pk=id)
            rent_car.delete()
            return redirect('main:welcome')
        except Exception as e:
            logger.error("Error: %s", e)


class SecretariatSiteView(LoginRequiredMixin, View):
    template = 'main/secretariat_menu.html'
    template_error = 'main/error_site.html'

    def get(self, request):
        try:
            return render(request, self.template)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)


class ShowTeamsListView(LoginRequiredMixin, View):
    template = 'main/teams_list.html'
    template_error = 'main/error_site.html'

    def get(self, request):
        try:
            teams = Team.objects.all().filter(active=True).order_by("priority")
            context = {'teams': teams}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)


class NewTeamView(LoginRequiredMixin, View):
    template = 'main/team_form_popup.html'
    template_error = 'main/error_site.html'
    form_class = TeamForm

    def get(self, request):
        try:
            form = self.form_class()
            context = {'team_form': form, 'new': True}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)

    def post(self, request):
        try:
            form = self.form_class(request.POST or None)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.active = True
                form.save()
                return redirect('main:show_teams_list')
            context = {'team_form': form, 'new': True}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)


class EditTeamView(LoginRequiredMixin, View):
    template = 'main/team_form_popup.html'
    template_error = 'main/error_site.html'
    form_class = TeamForm

    def get(self, request, id):
        try:
            team = get_object_or_404(Team, pk=id)
            form = self.form_class(instance=team)
            context = {'team_form': form, 'new': False, 'id': id}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)

    def post(self, request, id):
        try:
            team = get_object_or_404(Team, pk=id)
            form = self.form_class(request.POST or None, instance=team)
            if form.is_valid():
                form.save()
                return redirect('main:show_teams_list')
            context = {'team_form': form, 'new': False, 'id': id}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)


class EmployersListView(LoginRequiredMixin, View):
    template = 'main/employers_list.html'
    template_error = 'main/error_site.html'

    def get(self, request):
        try:
            employers = Employer.objects.all().filter(deleted=False).order_by("team__priority")
            try:
                last_date = Employer.objects.values("change").latest("change")
            except Employer.DoesNotExist:
                last_date = None

            secretariat = SecretariatTelephone.objects.last()
            context = {"employers": employers, "last_date": last_date, "secretariat": secretariat}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)


class NewEmployerView(LoginRequiredMixin, View):
    template = 'main/employer_form_popup.html'
    template_error = 'main/error_site.html'
    form_class = EmployerForm

    def get(self, request):
        try:
            form = self.form_class()
            context = {'employer_form': form, 'new': True}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}
            return render(request, self.template_error, context)

    def post(self, request):
        try:
            form = self.form_class(request.POST or None)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                form.save()
                return redirect('main:show_employers_list')
            context = {'employer_form': form, 'new': True}
            return render(request, self.template, context)
        except Exception as e:
            logger.error("Error: %s", e)
            context = {'error_message': f"Wystąpił błąd {e}"}

main/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{%static 'main/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap.rtl.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap.rtl.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-grid.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-grid.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-grid.rtl.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-grid.rtl.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-reboot.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-reboot.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-reboot.rtl.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-reboot.rtl.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-utilities.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-utilities.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-utilities.rtl.css'%}" rel="stylesheet">
    <link href="{%static 'main/bootstrap/css/bootstrap-utilities.rtl.min.css'%}" rel="stylesheet">
    <link href="{%static 'main/css/style.css'%}" rel="stylesheet">
    <!--    Select2-->
    <link href="{%static 'main/select2/css/select2.min.css'%}" rel="stylesheet">
    <!-- Bootstrap JS -->
    <script src="{%static 'main/bootstrap/js/bootstrap.bundle.js'%}"></script>
    <!--    jquery-->
    <script src="{%static 'main/bootstrap/jquery/jquery-3.6.0.min.js'%}"></script>
    <script src="{%static 'main/bootstrap/jquery/select2.min.js'%}"></script>
    <!-- icon -->
    <link rel="shortcut icon" href="{%static 'main/media/logo.ico'%}" type="x-icon">
    <!--    ICON SOURCE-->
    <link rel="stylesheet" href="{%static 'main/bootstrap-icons/bootstrap-icons.css'%}">

    <title>{%block title%} {%endblock%}</title>
</head>
<body>
<header class="d-flex flex-wrap justify-content-center p-2 mb-2 border-bottom body fixed-top bg-col">
    <a class="m-2 " href="{%url 'main:welcome'%}">
        <span class="bi bi-house my-home"></span>
    </a>
    {%if user.is_authenticated%}
    <a href="{%url 'main:give_access_to_modules'%}"
       class="d-flex align-items-center mb-md-0 me-md-auto text-dark text-decoration-none my-home margin-left-0">
        <span class="fs-5 bi bi-person-circle my-home padding-right-3" data-toggle="info" title="Użytkownik ID: {{user.username}}">
            {{user.first_name}} {{user.last_name}}</span></a>
    {%else%}
    <a href="{%url 'main:give_access_to_modules'%}"
       class="d-flex align-items-center mb-md-0 me-md-auto text-dark text-decoration-none margin-left-0">
        <span class="bi bi-people-fill my-home"> Użytkownik anonimowy</span>
    </a>
    {%endif%}
    <ul class="nav nav-pills mx-4">
        {%if user.is_authenticated and user.accessmodule.zok_team%}
        <li class="nav-item m-2">
            <a id="button-secretariat" href="{%url 'main:make_secretariat_site'%}"
               class="btn btn-sm btn-outline-success">
                <span>Sekretariat</span>
            </a>
        </li>
        {%endif%}
        {%if user.is_authenticated%}
        <li class="nav-item m-2">
            <a id="button-folder" href="{%url 'main:files'%}" class="btn btn-sm btn-outline-secondary my-btn">
                <span>Pliki do pobrania</span>
            </a>
        </li>
        {%endif%}
        <li class="nav-item m-2">
            <a id="button-units" href="{%url 'units:units_list'%}" class="btn btn-sm btn-outline-dark">
                <span>Jednostki Policji</span>
            </a>
        </li>
        {%if user.is_authenticated and user.accessmodule.investments_module%}
        <li class="nav-item m-2">
            <a id="button-investments" href="{%url 'investments:make_important_task_investments'%}"
               class="btn btn-sm btn-outline-dark ">
                <span>Inwestycje</span>
            </a>
        </li>
        {%endif%}
        {%if user.is_authenticated and user.accessmodule.zriwt_team or user.accessmodule.zm_team or user.accessmodule.zn_team or user.accessmodule.ze_team%}
        <li class="nav-item m-2">
            <a id="button-record" href=" {%url 'main:make_list_register'%}" class="btn btn-sm btn-outline-dark ">
                <span>Ewidencje</span>
            </a>
        </li>
        {%endif%}
        {%if user.is_authenticated and user.accessmodule.cpvdict_module%}
        <li class="nav-item m-2">
            <a id="button-cpv" href="{%url 'cpvdict:type_expense_list'%}" class="btn btn-sm btn-outline-dark ">
                <span>Rodzajowość WIiR</span>
            </a>
        </li>
        {%else%}
        <li class="nav-item m-2">
            <a id="button-cpvnotaut" href="{%url 'cpvdict:cpvlist'%}" class="btn btn-sm btn-outline-secondary ">
                <span>Słownik CPV</span>
            </a>
        </li>
        {%endif%}
        {%if user.is_authenticated%}
        <li class="nav-item m-2">
            <a href="{%url 'logout'%}" class="btn btn-sm btn-outline-danger ">
                <span class="bi bi-box-arrow-right"> Wyloguj</span>
            </a>
        </li>
        {%else%}
        <li class="nav-item m-2">
            <a href="{%url 'login'%}" class="btn btn-sm btn-success">
                <span class="bi bi-box-arrow-in-left"> Zaloguj</span>
            </a>
        </li>
        {%endif%}
    </ul>
</header>

<!-- Ikona dla menu mobilnego -->
<div class="d-lg-none fixed-top p-2 bg-light">
    <a class="navbar-toggler-icon" data-bs-toggle="collapse" href="#navbarNav" role="button" aria-expanded="false"
       aria-controls="navbarNav"></a>
</div>

<div class="footer body header-top pt-3">
    <!--    {% if breadcrumbs %}-->
    <!--    <span>{% include "dynamic_breadcrumbs/breadcrumbs.html" with breadcrumbs=breadcrumbs%}</span>-->
    <!--    {% endif %}-->
    {%block content%}

    {%endblock%}
</div>
<section class="fixed-bottom">
    <!-- Footer -->
    <footer class="text-center text-white" style="background-color: #0a4275;">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: CTA -->
            {%if user.is_authenticated%}
            <section class="">
                <p class="d-flex justify-content-center align-items-center">
                    <a class="text-decoration-none link-light"href="{%url 'main:telephone_list'%}"target="_blank">
                        <span>Spis telefonów</span>
                    </a>
                </p>
            </section>
            {%endif%}
            <!-- Section: CTA -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.3);">
            <span>© 2021 Wydział inwestycji i Remontów KWP w Poznaniu</span>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
</section>
<script>
    $(function () {
        $('[data-toggle="info"]').tooltip()
    })
</script>
</body>
</html>